/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTask: typeof import('./src/components/AddTask.vue')['default']
    AddTaskDialog: typeof import('./src/components/AddTaskDialog.vue')['default']
    DeleteTask: typeof import('./src/components/DeleteTask.vue')['default']
    DeleteTaskMessage: typeof import('./src/components/DeleteTaskMessage.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    ListItemArchive: typeof import('./src/components/ListItemArchive.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
